[package]
name = "ecs_scene"
version = "0.1.0"
edition = "2021"

[dependencies]
rein = { package = "rein-engine", path = "../..", features = ["ecs", "window"] }
glam = "0.31"
anyhow = "1"
hecs = "0.10"
